site_name: autoims
site_url: https://github.com/vandeplaslab/autoims-docs
site_author: Lukasz Migas
site_description: >-
  Suite of tools for image registration and visualisation.
  
# Repository
repo_name: vandeplaslab/autoims-docs
repo_url: https://github.com/vandeplaslab/autoims-docs

# Copyright
copyright: Copyright &copy; 2023 - present Van de Plas lab
extra_css:
  - assets/css/extra.css

theme:
  name: material
  logo: assets/icon.svg
  favicon: assets/icon.svg
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.expand
    - search.highlight
    - search.suggest
    - toc.integrate
    - toc.follow

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - changelog
  - attr_list
  - md_in_html
  - pymdownx.keys
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - autorefs
  - minify:
      minify_html: true
  - glightbox
  - offline

nav:
  - Home: index.md
  - Getting started: getting_started.md
  - Tasks: 
    - Glossary: tasks/glossary.md
    - User information: tasks/user.md
    - Pre-processing:
        - Convert raw data (single-dataset): tasks/pre_convert.md
        - Tags and names (single-dataset): tasks/pre_rename.md
        - Ion mobility alignment (single-dataset): tasks/pre_im_align.md
        - Mass alignment (single-dataset): tasks/pre_mz_align.md
        - Normalization (single-dataset): tasks/pre_normalization_single.md
        - Normalization (multi-dataset): tasks/pre_normalization_multi.md
        - Normalization (merged-project): tasks/pre_normalization_project.md
        - Average mass spectrum (single-dataset): tasks/pre_average_spectrum.md
        - Average ion mobility heatmap (single-dataset): tasks/pre_average_heatmap.md
        - Mass calibration (single-dataset): tasks/pre_mz_calibrate.md
        - Register GeoJSON masks from QuPath (single-dataset): tasks/pre_geojson_registration.md
        - Register image2image HDF5 masks (single-dataset): tasks/pre_image2image_registration.md
        - Merge single-datasets into project (merged-dataset): tasks/pre_merge_datasets.md
        - Select datasets into a subset (subset-dataset): tasks/pre_merge_datasets.md
    - Workflows:
        - Feature detection (single-dataset): tasks/wf_mz_detect_single.md
        - Feature detection (multi-dataset): tasks/wf_mz_detect_multi.md
        - Ion mobility feature detection (single-dataset): tasks/wf_im_detect_single.md
        - Extract ion centroids (single/multi-dataset): tasks/wf_mz_extract_centroids.md
        - Extract ion centroids (subset-dataset): tasks/wf_mz_extract_centroids_subset.md
        - Compute quality control metrics (multi-dataset): tasks/wf_qc_compute.md
        - Visualise quality control metrics (multi-dataset): tasks/wf_qc_visualise_multi.md
        - Visualise quality control metrics (subset-dataset): tasks/wf_qc_visualise_subset.md
        - Annotate mass spectra (single-dataset): tasks/wf_mz_annotate_single.md
        - Annotate mass spectrum (multi-dataset): tasks/wf_mz_annotate_multi.md
        - Annotate average mass spectrum (merged-project): tasks/wf_mz_annotate_project.md
        - Annotate mass spectrum (subset-dataset): tasks/wf_mz_annotate_subset.md
        - Unsupervised training (single-dataset): tasks/wf_unsupervised_single.md
        - Unsupervised training (merged-project): tasks/wf_unsupervised_project.md
        - Average mass spectrum / cluster (single-dataset): tasks/wf_unsupervised_spectrum_single.md
        - Compare mosaic images (single-dataset): tasks/wf_compare_single_mosaic.md
        - Compare mosaic images (multi-dataset): tasks/wf_compare_mosaic.md
        - Compare spectra (interactive, multi-dataset): tasks/wf_compare_mz_spectra_interactive.md
        - Compare peaks (interactive, multi-dataset): tasks/wf_compare_mz_peaks.md
        - Average mass spectrum / mask (single-dataset): tasks/wf_mask_spectrum_single.md
        - Average ion mobility heatmap / mask (single-dataset): tasks/wf_mask_heatmap_single.md
        - Supervised training (single-dataset): tasks/wf_supervised_single.md
        - Supervised training (merged-project): tasks/wf_supervised_project.md
        - Average mass spectrum / class (single-dataset): tasks/wf_supervised_spectrum_single.md
        - Process PASEF-MS1 imaging data (single-dataset): tasks/wf_pasef_ms1.md
        - Process PASEF-MS2 imaging data (single-dataset): tasks/wf_pasef_ms2.md
        - Compare spectra (one-vs-one; multi-dataset): tasks/wf_compare_mz_spectra_grid.md
        - Compare spectra (one-vs-one; single-dataset): tasks/wf_compare_mz_spectra_single_grid.md
        - Centroid ion statistics (multi-dataset): tasks/wf_centroids_ion_statistics.md
        - Peak ion statistics (multi-dataset): tasks/wf_mz_ion_statistics.md
    - Export:
        - Dataset to imzML (single-dataset): tasks/ex_export_imzml.md
  - Examples:
    - Multi-dataset: examples/multi-dataset.md
    - PASEF: examples/pasef.md
  - Requests/Bug reports: request.md
  - Changelog: changelog.md