site_name: autoims
site_url: https://github.com/vandeplaslab/autoims-docs
site_author: Lukasz Migas
site_description: >-
  Suite of tools for image registration and visualisation.
  
# Repository
repo_name: vandeplaslab/autoims-docs
repo_url: https://github.com/vandeplaslab/autoims-docs

# Copyright
copyright: Copyright &copy; 2023 - present Van de Plas lab
extra_css:
  - assets/css/extra.css

theme:
  name: material
  logo: assets/icon.svg
  favicon: assets/icon.svg
  palette:
    - scheme: default
      primary: grey
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: amber
      accent: yellow
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - search.highlight
    - search.suggest

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - changelog
  - attr_list
  - md_in_html
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - autorefs
  - minify:
      minify_html: true
  - glightbox
  - offline

nav:
  - Home: index.md
  - Getting started: getting_started.md
  - Tasks: 
    - Glossary: tasks/glossary.md
    - User information: tasks/user.md
    - Pre-processing:
      - Convert raw data: tasks/pre_convert.md
      # - Tags and names (WIP): tasks/pre_rename.md
      # - Mass alignment (WIP): tasks/pre_mz_align.md
      # - Ion mobility alignment (WIP): tasks/pre_im_align.md
      - Normalization (single-dataset): tasks/pre_normalization_single.md
      - Normalization (multi-dataset): tasks/pre_normalization_multi.md
      - Average heatmap: tasks/pre_average_heatmap.md
      - Average mass spectrum: tasks/pre_average_spectrum.md
      - Mass calibration: tasks/pre_mz_calibrate.md
    - Workflows:
      - Work in Progress: wip.md
      # - Peak detection (single-dataset) (WIP): tasks/wf_mz_detect_single.md
      # - Peak detection (multi-dataset) (WIP): tasks/wf_mz_detect_multi.md
      # - 2D feature detection (single-dataset) (WIP): tasks/wf_im_detect_single.md
      # - Extract centroids (WIP): tasks/wf_mz_extract_centroids.md
      # - Mass spectral quality control (WIP): tasks/mz_quality_control.md
      # - Annotate spectra (WIP): tasks/wf_mz_annotate.md
      # - Unsupervised training (single-dataset) (WIP): tasks/wf_unsupervised_single.md
      # - Unsupervised training (multi-dataset) (WIP): tasks/wf_unsupervised_multi.md
      # - Compare mosaics (stitched) (WIP): tasks/wf_compare_mosaic.md
      # - Compare peaks (interactive) (WIP): tasks/wf_compare_mz_peaks.md
      # - Compare spectra (interactive) (WIP): tasks/wf_compare_mz_spectra_interactive.md
      # - Compare spectra (grid) (WIP): tasks/wf_compare_mz_spectra_grid.md
    - Exports:
      - Work in Progress: wip.md
      # - Export average spectrum (WIP): tasks/ex_export_avg_spectrum.md
      # - Export to imzML (WIP): tasks/ex_export_imzml.md
      # - Export to OME-TIFF (WIP): tasks/ex_export_ometiff.md
      # - Export to MATLAB CSV (WIP): tasks/ex_export_fusion.md
  - Examples:
    - Multi-dataset: examples/multi-dataset.md
    - PASEF: examples/pasef.md
  - Requests/Bug reports: request.md
  - Changelog: changelog.md